# Generated by Django 4.2.16 on 2026-01-18 15:56
from __future__ import annotations

from django.db import migrations
from django.db import models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FSMTransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.TextField(
                        help_text="Primary key of the transitioned object"
                    ),
                ),
                (
                    "transition_name",
                    models.CharField(
                        help_text="Name of the transition method", max_length=255
                    ),
                ),
                (
                    "source_state",
                    models.CharField(
                        help_text="State before transition", max_length=255
                    ),
                ),
                (
                    "target_state",
                    models.CharField(
                        help_text="State after transition", max_length=255
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the transition occurred",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The model type that was transitioned",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="django_fsm__content_9a5058_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="django_fsm__timesta_cef858_idx"
                    ),
                ],
            },
        ),
    ]
