# Generated by Django 4.2.16 on 2026-01-18 17:08
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_fsm_rx", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsmtransitionlog",
            name="by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered the transition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fsmtransitionlog",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional description of the transition",
            ),
        ),
    ]
